1.จงเขียน array ที่มีแต่เลข 0 แบบ vector 10 ตัว และ แบบ Matrix 4x4

In [1]:
import numpy as np
arr1 = np.zeros(10)
arr1

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [2]:
arr1 = np.zeros((4,4))
arr1

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

---------------------------------------------------------------

2.จงเขียน array ที่มีแต่เลข 1 แบบ vector 5 ตัว และ แบบ Matrix 3x3

In [3]:
arr2 = np.ones(5)
arr2

array([1., 1., 1., 1., 1.])

In [4]:
arr2 = np.ones((3,3))
arr2

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

---

3.จงเขียน array ที่มีเป็นการ random ตัวเลข 20 ตัว แบบ float ค่าอยู่ในช่วง 10-99 แล้วนำแต่ละเลขยกกำลังสอง

In [5]:
arr3 = np.random.uniform(10,99,20)*2
arr3

array([ 82.39106277, 163.37983285, 163.3266139 , 186.41920974,
        26.52534701, 179.54795594,  32.45107793, 175.63002208,
        58.76467932,  47.22578276, 164.3386601 ,  65.40340086,
        60.17281244,  26.08384753, 137.73054332,  56.15310088,
        73.29178829, 116.66022419, 107.65975523, 164.92376961])

---------------------

4.ทำเหมือนข้อ 3 แต่เขียนแบบ List comprehension

In [6]:
import random as rm
lst = [rm.uniform(10, 99)**2 for i in range(20)]
lst

[438.16932915176636,
 4120.0896797964715,
 2275.376869720029,
 5737.450739273967,
 576.0267192930679,
 555.6868778279071,
 5604.90071137735,
 9291.254372687323,
 9439.65331677532,
 1497.071921855949,
 761.2566702077246,
 1338.536139320731,
 9652.667847712108,
 1974.3442097631475,
 5918.8334417026235,
 6575.340908922771,
 1078.7952252868192,
 1366.8124708395626,
 1183.2466864682724,
 4552.00685083465]

---------------------

5.นำข้อ 3 และ 4 มาเปรียบเวลากัน โดยใช้ฟังก์ชั่น time.time( ) เพื่อจับเวลา แสดงผลลัพธ์ในรูปแบบมิลลิวินาที

In [7]:
import time
milliseconds1 = int(round(time.time() * 1000))
arr3 = np.random.uniform(10,99,20)*2
milliseconds2 = int(round(time.time() * 1000))
lst = [rm.uniform(10, 99)**2 for i in range(20)]
milliseconds3 = int(round(time.time() * 1000))
#print(milliseconds1)
#print(milliseconds2)
#print(milliseconds3)
numpyArrTime = (milliseconds2-milliseconds1)
lstTime = (milliseconds3-milliseconds2)
 
print( 'numpyArrTime ใช้เวลา : ', numpyArrTime, 'milliseconds')
print( 'list ใช้เวลา : ', lstTime, 'milliseconds')

numpyArrTime ใช้เวลา :  0 milliseconds
list ใช้เวลา :  0 milliseconds


---------------------

6.จงเขียน array ที่ใช้ฟังก์ชั่นใน numpy ได้เลข 10 ถึง 1000

In [8]:
arr6 = np.arange(10,1001)
arr6

array([  10,   11,   12,   13,   14,   15,   16,   17,   18,   19,   20,
         21,   22,   23,   24,   25,   26,   27,   28,   29,   30,   31,
         32,   33,   34,   35,   36,   37,   38,   39,   40,   41,   42,
         43,   44,   45,   46,   47,   48,   49,   50,   51,   52,   53,
         54,   55,   56,   57,   58,   59,   60,   61,   62,   63,   64,
         65,   66,   67,   68,   69,   70,   71,   72,   73,   74,   75,
         76,   77,   78,   79,   80,   81,   82,   83,   84,   85,   86,
         87,   88,   89,   90,   91,   92,   93,   94,   95,   96,   97,
         98,   99,  100,  101,  102,  103,  104,  105,  106,  107,  108,
        109,  110,  111,  112,  113,  114,  115,  116,  117,  118,  119,
        120,  121,  122,  123,  124,  125,  126,  127,  128,  129,  130,
        131,  132,  133,  134,  135,  136,  137,  138,  139,  140,  141,
        142,  143,  144,  145,  146,  147,  148,  149,  150,  151,  152,
        153,  154,  155,  156,  157,  158,  159,  1

---------------------

7.จงเขียน array ที่ใช้ฟังก์ชั่นใน numpy ได้เลขคู่ 10 ถึง 2000 

In [9]:
arr7 = np.arange(10,2002,2)
arr7

array([  10,   12,   14,   16,   18,   20,   22,   24,   26,   28,   30,
         32,   34,   36,   38,   40,   42,   44,   46,   48,   50,   52,
         54,   56,   58,   60,   62,   64,   66,   68,   70,   72,   74,
         76,   78,   80,   82,   84,   86,   88,   90,   92,   94,   96,
         98,  100,  102,  104,  106,  108,  110,  112,  114,  116,  118,
        120,  122,  124,  126,  128,  130,  132,  134,  136,  138,  140,
        142,  144,  146,  148,  150,  152,  154,  156,  158,  160,  162,
        164,  166,  168,  170,  172,  174,  176,  178,  180,  182,  184,
        186,  188,  190,  192,  194,  196,  198,  200,  202,  204,  206,
        208,  210,  212,  214,  216,  218,  220,  222,  224,  226,  228,
        230,  232,  234,  236,  238,  240,  242,  244,  246,  248,  250,
        252,  254,  256,  258,  260,  262,  264,  266,  268,  270,  272,
        274,  276,  278,  280,  282,  284,  286,  288,  290,  292,  294,
        296,  298,  300,  302,  304,  306,  308,  3

---------------------

8.จงเขียน array ที่ใช้ฟังก์ชั่นใน numpy ได้เลขคี่ 12 ถึง 900

In [10]:
arr7 = np.arange(13,900,2)
arr7

array([ 13,  15,  17,  19,  21,  23,  25,  27,  29,  31,  33,  35,  37,
        39,  41,  43,  45,  47,  49,  51,  53,  55,  57,  59,  61,  63,
        65,  67,  69,  71,  73,  75,  77,  79,  81,  83,  85,  87,  89,
        91,  93,  95,  97,  99, 101, 103, 105, 107, 109, 111, 113, 115,
       117, 119, 121, 123, 125, 127, 129, 131, 133, 135, 137, 139, 141,
       143, 145, 147, 149, 151, 153, 155, 157, 159, 161, 163, 165, 167,
       169, 171, 173, 175, 177, 179, 181, 183, 185, 187, 189, 191, 193,
       195, 197, 199, 201, 203, 205, 207, 209, 211, 213, 215, 217, 219,
       221, 223, 225, 227, 229, 231, 233, 235, 237, 239, 241, 243, 245,
       247, 249, 251, 253, 255, 257, 259, 261, 263, 265, 267, 269, 271,
       273, 275, 277, 279, 281, 283, 285, 287, 289, 291, 293, 295, 297,
       299, 301, 303, 305, 307, 309, 311, 313, 315, 317, 319, 321, 323,
       325, 327, 329, 331, 333, 335, 337, 339, 341, 343, 345, 347, 349,
       351, 353, 355, 357, 359, 361, 363, 365, 367, 369, 371, 37

---------------------

9.จงสร้าง identity matrix แบบ 4x4

In [11]:
arr9 = np.eye(4,4)
arr9

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

---------------------

10.จงหาว่า array ที่มีสมาชิก 100 ตัว เริ่มจาก 5 ถึง 25 มีผลต่างแต่ละตัวเท่ากับเท่าใด

In [12]:
arr10 = np.linspace(5,25,100)
arr10

array([ 5.        ,  5.2020202 ,  5.4040404 ,  5.60606061,  5.80808081,
        6.01010101,  6.21212121,  6.41414141,  6.61616162,  6.81818182,
        7.02020202,  7.22222222,  7.42424242,  7.62626263,  7.82828283,
        8.03030303,  8.23232323,  8.43434343,  8.63636364,  8.83838384,
        9.04040404,  9.24242424,  9.44444444,  9.64646465,  9.84848485,
       10.05050505, 10.25252525, 10.45454545, 10.65656566, 10.85858586,
       11.06060606, 11.26262626, 11.46464646, 11.66666667, 11.86868687,
       12.07070707, 12.27272727, 12.47474747, 12.67676768, 12.87878788,
       13.08080808, 13.28282828, 13.48484848, 13.68686869, 13.88888889,
       14.09090909, 14.29292929, 14.49494949, 14.6969697 , 14.8989899 ,
       15.1010101 , 15.3030303 , 15.50505051, 15.70707071, 15.90909091,
       16.11111111, 16.31313131, 16.51515152, 16.71717172, 16.91919192,
       17.12121212, 17.32323232, 17.52525253, 17.72727273, 17.92929293,
       18.13131313, 18.33333333, 18.53535354, 18.73737374, 18.93

---------------------

11.จงเขียนฟังก์ชั่น random ตัวเลขแบบ float ในช่วง 0-1 ขึ้นมา 1 ตัว

In [13]:
arr11 = np.random.rand(1)
arr11

array([0.0802472])

---------------------

12.จงเขียนฟังก์ชั่นที่ random ตัวเลขแบบ int ในช่วง 50-100 โดยให้อยู่ในรูป Matrix 4x4 และ Transpose

In [14]:
arr12 = np.random.randint(50,101,(4,4))
print(arr12)
print('------------------------')
print(arr12.T)

[[95 74 98 55]
 [50 89 98 88]
 [79 80 94 57]
 [56 70 91 61]]
------------------------
[[95 50 79 56]
 [74 89 80 70]
 [98 98 94 91]
 [55 88 57 61]]


---------------------

13.ให้ array ที่กำหนด จงเขียนโค้ดที่เลือกเฉพาะ 8,9,13,14

In [15]:
arr13 = np.arange(1,26).reshape((5,5))
print(arr13)
print('------------------------')
print(arr13[1:3,2:4])

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]
 [21 22 23 24 25]]
------------------------
[[ 8  9]
 [13 14]]


---------------------

14.ให้ array ที่กำหนด จงเขียนโค้ดที่เลือกเฉพาะ 18,19,20

In [16]:
arr14 = np.arange(1,26).reshape((5,5))
print(arr14)
print('------------------------')
print(arr14[3,2:])

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]
 [21 22 23 24 25]]
------------------------
[18 19 20]


---------------------

15.ให้ array ที่กำหนด จงเขียนโค้ดที่เลือกเฉพาะ 16,17,21,22

In [17]:
arr15 = np.arange(1,26).reshape((5,5))
print(arr15)
print('------------------------')
print(arr15[3:,0:2])

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]
 [21 22 23 24 25]]
------------------------
[[16 17]
 [21 22]]


---------------------

16.ให้ array ที่กำหนด จงเขียนโค้ดที่เลือกทั้งแถว 3

In [18]:
arr15 = np.arange(1,26).reshape((5,5))
print(arr15)
print('------------------------')
print(arr15[2])

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]
 [21 22 23 24 25]]
------------------------
[11 12 13 14 15]


---------------------

17.จงเขียนโค้ดที่ทำให้ได้ array นี้ออกมา

In [19]:
arr17 = np.arange(1,26).reshape((5,5))
arr17

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25]])

---------------------

18.จงเขียนโปรแกรมสุ่มเลขจำนวนเต็มในช่วง 10-100 ออกมาอยู่ใน matrix 5x5 และใช้ If-else เช็คทีละตัวว่าตัวใดบ้างที่มีค่ามากกว่า 50 และปริ้นออกมา

In [20]:
arr18 = np.random.randint(10,101,(5,5))
print(arr18)
rows = len(arr18)
columns = len(arr18[0]) 
for r in range(rows):
    for c in range(columns):
        if arr18[r][c] > 50:
            print(arr18[r][c])

[[49 77 99 40 47]
 [87 74 48 35 41]
 [25 24 68 80 68]
 [18 54 76 11 31]
 [65 64 32 73 29]]
77
99
87
74
68
80
68
54
76
65
64
73


---------------------

19.จงเขียนโปรแกรมสุ่มเลขจำนวนเต็มในช่วง 10-100 ออกมาอยู่ใน matrix 5x5 และใช้ conditional selection เช็คว่าตัวใดบ้างมีค่ามากกว่า 40 นำมาใส่ List ที่สร้างใหม่ และปริ้นออกมา

In [21]:
arr19 = np.random.randint(10,101,(5,5))
print(arr19) 
boolArr = arr19 > 40 
lst = []
lst = arr19[boolArr]
lst

[[68 21 20 49 16]
 [38 51 65 65 94]
 [84 25 78 43 68]
 [50 15 51 18 79]
 [29 59 48 15 69]]


array([68, 49, 51, 65, 65, 94, 84, 78, 43, 68, 50, 51, 79, 59, 48, 69])

---------------------

20.เขียนโปรแกรมรับค่าจากผู้ใช้ให้ป้อนเลข 9 ตัว แต่ละตัวต้องไม่ซ้ำกันและมีค่าอยู่ในช่วง 10-100 นำเลข 9 ตัวนั้นมาทำเป็น matrix 3x3 และ transport และหาเลขอยู่ตำแหน่งที่ (2,2)

In [22]:
lst = [] 
for i in range(9):
    while 1 :
        num1 = int(input('input number : '))
        if (num1 >= 10 and num1 <= 100 and num1 not in lst):
            lst.append(num1)
            break
        
print('\nMatrix 3x3\n',np.array(lst).reshape(3,3))
print('\nTransport\n', np.array(lst).reshape(3,3).T) 
print('\nArray (2,2)\n', np.array(lst).reshape(3,3).T[2,2]) 

input number : 11
input number : 22
input number : 33
input number : 44
input number : 55
input number : 66
input number : 77
input number : 88
input number : 88
input number : 88
input number : 111
input number : 1
input number : 99

Matrix 3x3
 [[11 22 33]
 [44 55 66]
 [77 88 99]]

Transport
 [[11 44 77]
 [22 55 88]
 [33 66 99]]

Array (2,2)
 99


---------------------